#!/bin/bash

clear

wg_interface=$2
wg_client_net="10.0.0.0/24"
wg_port="51820"
client_name="client"
public_key="empty"
allowed_ips="0.0.0.0/0"

prompt_continue() {
    echo
    echo $1 "Press ENTER to continue"
    read
    clear
}

prompt_continue_or_exit() {
    echo
    echo "Press ENTER to continue."
    echo "Press CTRL + C to exit."
    read
    clear
}

generate_interface_config() {
    echo "[Interface]"                                                               | sudo tee /etc/wireguard/$wg_interface.conf > /dev/null
    echo "PrivateKey = $(sudo cat /etc/wireguard/keys/$wg_interface/private.key)"    | sudo tee -a /etc/wireguard/$wg_interface.conf > /dev/null
    echo "Address = $wg_client_net"                                                  | sudo tee -a /etc/wireguard/$wg_interface.conf > /dev/null
    echo "ListenPort = $wg_port"                                                     | sudo tee -a /etc/wireguard/$wg_interface.conf > /dev/null
    echo                                                                             | sudo tee -a /etc/wireguard/$wg_interface.conf > /dev/null
}

# generate public & private key
generate_keys() {
    # make sure all files have correct permissions
    sudo mkdir -p /etc/wireguard/keys/$wg_interface
    sudo touch /etc/wireguard/keys/$wg_interface/private.key
    sudo touch /etc/wireguard/keys/$wg_interface/public.key
    sudo touch /etc/wireguard/$wg_interface.conf
    sudo chown -R root:root /etc/wireguard
    sudo chmod -R 700 /etc/wireguard
    # generate keys
    umask 077
    wg genkey | sudo tee /etc/wireguard/keys/$wg_interface/private.key > /dev/null
    sudo cat /etc/wireguard/keys/$wg_interface/private.key | wg pubkey | sudo tee /etc/wireguard/keys/$wg_interface/public.key > /dev/null
}

# remove client from interface config
remove_client() {
    sudo sed -i "/### Name: $1/,/##########/d" /etc/wireguard/$wg_interface.conf
}

# print help message
print_help() {
    echo "Invalid arguments. Available commands:"
    echo "<INTERFACE> must be the name of the interface you want to modify."
    echo
    echo "> $(basename "$0") create <INTERFACE>"
    echo "Sets up a new wireguard interface."
    echo
    echo "> $(basename "$0") delete <INTERFACE>"
    echo "Deletes this wireguard interface."
    echo
    echo "> $(basename "$0") generate-keys <INTERFACE>"
    echo "Generates new public and private key for this interface."
    echo
    echo "> $(basename "$0") add-client <INTERFACE>"
    echo "Adds a new client to this interface."
    echo
    echo "> $(basename "$0") remove-client <INTERFACE>"
    echo "Removes a client from this interface."
    echo
}

#
# print help if <INTERFACE> parameter is not defined
#
[[ $wg_interface == "" ]] && print_help && exit

#
# create
#
if [[ $1 == "create" ]]; then   
    
    # input: wg_client_net
    echo "Enter IPv4 address range that clients will be assigned to. [def: $wg_client_net]"
    read -p ">>> "
    if [[ $REPLY != "" ]]; then
        wg_client_net=$REPLY
    fi
    clear

    # input: wg_port
    echo "Enter public port to connect to the wireguard service. Make sure port is free. [def: $wg_port]"
    read -p ">>> "
    if [[ $REPLY != "" ]]; then
        wg_port=$REPLY
    fi
    clear

    # summary
    echo "wg_client_net =  $wg_client_net"
    echo "wg_port =        $wg_port"
    echo
    prompt_continue_or_exit

    # generate public & private key
    generate_keys

    # generate basic interface config
    generate_interface_config

# 
# delete
#
elif [[ $1 == "delete" ]]; then
    
    # stop interface
    sudo wg-quick down $wg_interface

    # delete files
    sudo rm /etc/wireguard/$wg_interface.conf
    sudo rm -r /etc/wireguard/keys/$wg_interface
    

#
# generate-keys
#
elif [[ $1 == "generate-keys" ]]; then
    
    # generate keys and interface config
    generate_keys
    generate_interface_config

#
# add-client
#
elif [[ $1 == "add-client" ]]; then

    # input: client_name
    echo "Enter name for new client. Make sure it is unique. [def: $client_name]"
    read -p ">>> "
    if [[ $REPLY != "" ]]; then
        client_name=$REPLY
    fi
    clear

    # input: public_key
    echo "Enter public key of client. [def: $public_key]"
    read -p ">>> "
    if [[ $REPLY != "" ]]; then
        public_key=$REPLY
    fi
    clear

    # input: allowed_ips
    echo "Enter network that client should have access to. [def: $allowed_ips]"
    read -p ">>> "
    if [[ $REPLY != "" ]]; then
        allowed_ips=$REPLY
    fi
    clear

    # summary
    echo "client_name =  $client_name"
    echo "public_key =   $public_key"
    echo "allowed_ips =  $allowed_ips"
    echo
    prompt_continue_or_exit

    # remove existing client
    remove_client $client_name

    # add client to interface config
    echo "### Name: $client_name"         | sudo tee -a /etc/wireguard/$wg_interface.conf > /dev/null
    echo "[Peer]"                         | sudo tee -a /etc/wireguard/$wg_interface.conf > /dev/null
    echo "PublicKey = $public_key"        | sudo tee -a /etc/wireguard/$wg_interface.conf > /dev/null
    echo "AllowedIPs = $allowed_ips"      | sudo tee -a /etc/wireguard/$wg_interface.conf > /dev/null
    echo "##########"                     | sudo tee -a /etc/wireguard/$wg_interface.conf > /dev/null

#
# remove-client
#
elif [[ $1 == "remove-client" ]]; then

    # input: client_name
    echo "Enter name of client that should be removed. [def: $client_name]"
    read -p ">>> "
    if [[ $REPLY != "" ]]; then
        client_name=$REPLY
    fi
    clear

    # remove existing client
    remove_client $client_name

#
# help
#
else
    print_help
fi
